name: Build china-list.dat
on:
  push:
    branches:
      - master
    paths:
      - 'data/*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.x.y
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Set variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
        shell: bash
      - name: Sleep 5 min
        run: |
          sleep 5m
      - name: Checkout codebase
        uses: actions/checkout@v2.3.4
        with:
          path: code
      - name: Build china-list.dat file
        run: |
          cd code/ || exit 1
          go run ./ --outputdir=../
          cd ../ && rm -rf code/
      - name: Generate china-list.dat sha256 hash
        run: |
          sha256sum china-list.dat > china-list.dat.sha256sum
      - name: Generate XZ
        run: |
          xz -z -9 -k china-list.dat
          sha256sum china-list.dat.xz > china-list.dat.xz.sha256sum
      - name: Configuration environment
        run: |
          git config --global user.email "dctxmei@yandex.com"
          git config --global user.name "Dct Mei"
      - name: Git push assets to "release" branch
        run: |
          git init
          git checkout -b release
          git add china-list.dat*
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release
      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
      - name: Upload china-list.dat
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./china-list.dat
          asset_name: china-list.dat
          asset_content_type: application/octet-stream
      - name: Upload china-list.dat sha256sum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./china-list.dat.sha256sum
          asset_name: china-list.dat.sha256sum
          asset_content_type: text/plain
      - name: Upload china-list.dat.xz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./china-list.dat.xz
          asset_name: china-list.dat.xz
          asset_content_type: application/octet-stream
      - name: Upload china-list.dat.xz sha256sum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./china-list.dat.xz.sha256sum
          asset_name: china-list.dat.xz.sha256sum
          asset_content_type: text/plain
